### PR TITLE
Add methods setup process afterscript

### LINKED ISSUE #321: Use `methods.setup_process_afterscript()` for process logs
We should incorporate the new `methods.setup_process_afterscript()` from https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/64 into this pipeline.

Under the new method, log files are automatically saved to `${params.log_output_dir}/process-log/${task.ext.log_dir}${task.ext.log_dir_suffix}/` (no need to specify a `publishDir` directive).

`${task.ext.log_dir}` defaults to `${task.process.replace(':', '/')}`.
`${task.ext.log_dir_suffix}` defaults to a blank string.

The key steps are:
1. Add `methods.setup_process_afterscript()` to `methods.setup()`.
2. For each Nextflow process:
    1. Remove the `file ".command.*"` `output` directive.
    2. Add `ext log_dir { ... }` and `ext log_sur_suffix { ... }` directives, if appropriate.
    3. Remove the `publishDir` directive with `pattern: ".command.*"`.

As an example, this `publishDir` directive...
https://github.com/uclahs-cds/pipeline-align-DNA/blob/05275a7c81c9077e7f5fa41e48c7156494edfbdb/module/align_DNA_BWA_MEM2.nf#L35-L38

... should be replaced with this directives:

```nextflow
ext log_dir { "${params.bwa_version}/${task.process.split(':')[1].replace('_', '-')}" }
ext log_dir_suffix { "/${library}/${lane}" }
```

See https://github.com/uclahs-cds/pipeline-recalibrate-BAM/pull/76/files for a full example.

### PR DESCRIPTION
**Pull request by j2salmingo**
# Description

## Testing Results

- NFTest
  - input:
     sample_id: a_mini_n2_spark
     input_csv: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/input/csv/a_mini_n2.csv
     reference_fasta_bwa: /hot/ref/tool-specific-input/BWA-MEM2-2.2.1/GRCh38-BI-20160721/index/genome.fa
     reference_fasta_index_files_bwa: /hot/ref/tool-specific-input/BWA-MEM2-2.2.1/GRCh38-BI-20160721/index/genome.fa.*
     reference_fasta_hisat2: /hot/ref/reference/GRCh38-BI-20160721/Homo_sapiens_assembly38.fasta
     reference_fasta_index_files_hisat2: /hot/ref/tool-specific-input/HISAT2-2.2.1/GRCh38-BI-20160721/index/Homo_sapiens_assembly38.*.ht2

  - output:
     work_dir: /scratch/185380
     output_dir: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/unreleased/jsalmingo-use-methods-setup-process-afterscript/a_mini_n2-spark
     output_dir_base_bwa: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/unreleased/jsalmingo-use-methods-setup-process-afterscript/a_mini_n2-spark/align-DNA-10.1.0/a_mini_n2_spark
     output_dir_base_hisat2: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/unreleased/jsalmingo-use-methods-setup-process-afterscript/a_mini_n2-spark/align-DNA-10.1.0/a_mini_n2_spark
     log_output_dir_bwa: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/unreleased/jsalmingo-use-methods-setup-process-afterscript/a_mini_n2-spark/align-DNA-10.1.0/a_mini_n2_spark/log-align-DNA-10.1.0-20240625T211311Z/
     log_output_dir_hisat2: /hot/software/pipeline/pipeline-align-DNA/Nextflow/development/unreleased/jsalmingo-use-methods-setup-process-afterscript/a_mini_n2-spark/align-DNA-10.1.0/a_mini_n2_spark/log-align-DNA-10.1.0-20240625T211311Z/

# Checklist

- [X] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [X] I have reviewed the [Nextflow pipeline standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3193890/Nextflow+pipeline+standardization).

- [X] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)]-\[brief_description_of_branch].
  
- [X] I have set up the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request, or the branch protection rule has already been set up.

- [X] I have added my name to the contributors listings in the ``manifest`` block in the `nextflow.config` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [X] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [X] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [X] I have tested the pipeline on at least one A-mini sample with aligner setting to `BWA-MEM2`, `HISAT2`, and both. The paths to the test config files and output directories were attached in the [Testing Results](#testing-results) section.

### CODE REVIEW

**Review by yashpatel6 — COMMENTED** [review]
We'll want to do this for all of the processes

**Comment by nwiltsie** [comment]
I'll take a look today!

**Review by nwiltsie — APPROVED** [review]
Looks great!

**Pull request merged**
